title: Genics Blog
email: contact@genicsblog.com
description: >-
  An open source developer publication aimed at sharing well explained
  tutorials on various topics for the developer community.
baseurl: ""
url: "https://genicsblog.com"
permalink: /:title
twitter_username: "genicsblog"
github_username: "genicsblog"
github_repo: "genicsblog/genicsblog.github.io"
staticman_url: "https://comments.genicsblog.com"
google_analytics: "UA-145769474-1"
adsense-data-ad-client: "ca-pub-8114751086331659"
adsense-data-display-ad-slot: "8698895132"
adsense-data-infeed-ad-slot: "3535897708"

defaults:
  -
    scope:
      path: "_drafts/*.md"
    values:
      sitemap: false

collections:
  series:
    permalink: /series/:name
    output: true
  contributors:
    permalink: /contributor/:name
    output: true
  drafts:
    permalink: /draft/:name
    output: true

extlinks:
  attributes: {rel: nofollow noopener noreferrer, target: _blank}
  rel_exclude: ["genicsblog.com", "jekyllex.xyz"]
          
# Build settings
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-minifier
  - jekyll-archives
  - jekyll-hostname
  - jekyll-paginate-v2
  - jekyll-loading-lazy
  - jekyll-redirect-from

pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true

  categories: 
    layouts: 
      - 'archive.html'
    title: 'Posts in category #:cat'
    permalink: '/category/:cat'
    silent: false
    slugify:
      mode: 'default'
      case: true

  collections:
    enabled: false

  tags:
    layouts: 
      - 'archive.html'
    title: 'Posts tagged with #:tag'
    permalink: '/tag/:tag'
    silent: false
    slugify:
      mode: 'default'
      case: true

postcss:
  cache: false

jekyll-minifier:
  exclude: 
    - "sitemap.xml"
    - "search.json"
    - "assets/css/theme.css"
  uglifier_args:
    harmony: true
    
include: 
  - _pages
  - .nojekyll

exclude:
  - _scripts/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - staticman.yml
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json
  - README.md
  - Dockerfile
