name: Validate contributors

on:
  pull_request_target:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${{github.head_ref}})"
      id: extract_branch

    - uses: actions/checkout@v2
      with:
        repository: "${{ github.event.pull_request.user.login }}/genicsblog.github.io"
        ref: "${{ steps.extract_branch.outputs.branch }}"

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          contributors:
            - '_data/contributors.yml'

    - name: Get all changed files
      if: steps.filter.outputs.contributors == 'true'
      id: files
      uses: Ana06/get-changed-files@v2.1.0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install python dependencies
      if: steps.filter.outputs.contributors == 'true'
      run: |
        pip install PyYAML python-frontmatter requests

    - name: Get validation script from main branch
      if: steps.filter.outputs.contributors == 'true'
      run: |
        rm -rf _scripts
        wget https://raw.githubusercontent.com/genicsblog/genicsblog.github.io/main/_scripts/validate-contributors.py -P _scripts

    - name: Validate contributors
      if: steps.filter.outputs.contributors == 'true'
      run: |
        echo "${{ steps.files.outputs.all }}" >> temp.txt
        python _scripts/validate-contributors.py ${{ github.event.pull_request.user.login }}
        rm temp.txt

    - name: Add contributor pages to PR
      if: steps.filter.outputs.contributors == 'true'
      run: |
        git config user.name "Gourav Khunger"
        git config user.email "46792249+gouravkhunger@users.noreply.github.com"
        git add _contributors
        git commit -m "Add contributor pages"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
